### ISSUE TITLE
install.sql : missing comma

### ISSUE THREAD

**Issue by artlab23** [dannytsang/energyathome#19]
mysql -u root -p < /energyathome/install/install.sql
Enter password: 
ERROR 1064 (42000) at line 40: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'datetime NOT NULL,
  `channel_id` int(11) NOT NULL,
  `data` float DEFAULT NU...' at line 3

Comma missing from the end of line 41 : " `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY"

Other than that, thanks again, Danny! :)

**Comment by dannytsang** [comment]
@artlab23 I will take a look and update the script. Thank you for reporting it.
